services:
  - type: web
    name: fief-server
    region: frankfurt
    env: docker
    healthCheckPath: /healthz
    preDeployCommand: sh /app/pre-deploy.sh
    envVars:
      - fromGroup: fief
      - key: DATABASE_URL
        fromDatabase:
          name: fief-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fief-redis
          property: connectionString
  - type: worker
    name: fief-worker
    region: frankfurt
    env: docker
    dockerCommand: fief run-worker -p 1 -t 1
    envVars:
      - fromGroup: fief
      - key: DATABASE_URL
        fromDatabase:
          name: fief-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fief-redis
          property: connectionString
  - type: redis
    name: fief-redis
    region: frankfurt
    ipAllowList: []
    maxmemoryPolicy: noeviction

databases:
  - name: fief-db
    region: frankfurt
    databaseName: fief
    user: fief
    ipAllowList: []

envVarGroups:
  - name: fief
    envVars:
      - key: FIEF_VERSION
        value: 0.28.5
      - key: DATABASE_TYPE
        value: POSTGRESQL
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: FORWARDED_ALLOW_IPS
        value: '*'
      - key: ALLOW_ORIGIN_REGEX
        sync: false
      - key: SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false
      - key: EMAIL_PROVIDER
        sync: false
      - key: EMAIL_PROVIDER_PARAMS
        sync: false
      - key: FIEF_DOMAIN
        sync: false
      - key: FIEF_CLIENT_ID
        generateValue: true
      - key: FIEF_CLIENT_SECRET
        generateValue: true
      - key: FIEF_MAIN_USER_EMAIL
        sync: false
      - key: FIEF_MAIN_USER_PASSWORD
        sync: false
